nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.4.0.cjs

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '*'
  '@graphql-codegen/cli@*':
    peerDependencies:
      typescript: '*'
  '@mdx-js/loader@*':
    peerDependencies:
      react: '*'
  '@storybook/core@*':
    peerDependencies:
      typescript: '*'
  '@storybook/addon-docs@*':
    peerDependencies:
      typescript: '*'
  '@storybook/addon-essentials@*':
    peerDependencies:
      typescript: '*'
  '@storybook/react@*':
    peerDependencies:
      typescript: '*'
  'graphql-config@*':
    peerDependencies:
      typescript: '*'
  'next-urql@*':
    peerDependencies:
      react-is: '*'
  'react-dev-utils@*':
    peerDependencies:
      typescript: '*'
      webpack: '*'
