nodeLinker: node-modules

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '*'
  '@graphql-codegen/cli@*':
    peerDependencies:
      typescript: '*'
  '@mdx-js/loader@*':
    peerDependencies:
      react: '*'
  '@storybook/addon-essentials@*':
    dependencies:
      '@storybook/components': '*'
      '@storybook/core-events': '*'
      '@storybook/theming': '*'
  '@storybook/addon-postcss@*':
    peerDependencies:
      webpack: '*'
  '@storybook/core@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@storybook/core-server@*':
    peerDependencies:
      '@babel/core': '*'
  '@storybook/csf-tools@*':
    peerDependencies:
      '@babel/core': '*'
  'graphql-config@*':
    peerDependencies:
      typescript: '*'
  'react-dev-utils@*':
    peerDependencies:
      typescript: '*'
      webpack: '*'
  'react-instantsearch-dom@*':
    peerDependencies:
      algoliasearch: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.4.2.cjs
