name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Linting
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: eslint ./

      - name: Typechecking
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: tsc

      - name: Tests
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
